# Base image
FROM node:16-alpine
 
USER node

# specific stupid node things because node_modules
# is created from the 'root' user and tries to 
# access it as the 'node' user
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
 
CMD ["npm", "start"]

# docker run -it -p 3000:3000 -v /home/node/app/node_modules -v ~/my-project-directory:/home/node/app jrobe/cra