name: Docker Build, Test, and Deploy Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -f Dockerfile.dev -t jrobe/docker-react .

      - name: Run tests in Docker container
        run: docker run -e CI=true jrobe/docker-react npm run test

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL

      - name: Build and push Docker image to ACR
        run: |
          az acr login --name udemyapp1
          docker tag jrobe/docker-react udemyapp1.azurecr.io/docker-react:latest
          docker push udemyapp1.azurecr.io/docker-react:latest

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: udemy-docker-react
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: 'udemyapp1.azurecr.io/docker-react:latest'
